FROM envoyproxy/envoy:latest

RUN apt update && apt install -y python3 python3-pip \
&& pip3 install --upgrade pip \
&& pip install -q Flask==0.11.1 requests==2.18.4 \
&& pip install grpcio googleapis-common-protos \
&& pip install consulate \
&& mkdir /code 

RUN apt install -y netcat

COPY ./services/proto/rpc/src/room_pb2* /code/
COPY ./services/zonesvr/service.py /code

COPY ./services/zonesvr/start_service.sh /usr/local/bin/start_service.sh
COPY ./services/zonesvr/service-envoy.yaml /etc/service-envoy.yaml
COPY ./services/3rd/consul /usr/bin/

RUN mkdir /etc/consul.d

CMD chmod u+x /usr/local/bin/start_service.sh /usr/bin/consul
ENTRYPOINT ["sh", "/usr/local/bin/start_service.sh" ]
