version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-http-gateway
    volumes:
      - ./http-gateway.yaml:/etc/http-gateway.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  zonesvr:
    build:
      context: ./zonesvr
      dockerfile: Dockerfile-zonesvr
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - zonesvr1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  envoymesh: {}
