FROM envoyproxy/envoy:latest

RUN apt update && apt install -y python3 python3-pip \
&& pip3 install --upgrade pip \
&& pip install grpcio googleapis-common-protos \
&& pip install consulate \
&& mkdir /code \
&& apt install -y netcat

RUN apt install -y curl tcpdump vim

COPY ./services/3rd/consul /usr/bin/
COPY ./services/envoy-xds/envoy-xds /usr/local/bin/envoy-xds
COPY ./services/envoy-xds/start_service.sh /usr/local/bin/start_service.sh

RUN mkdir /etc/consul.d
RUN chmod u+x /usr/local/bin/start_service.sh /usr/bin/consul

ENTRYPOINT ["sh", "/usr/local/bin/start_service.sh" ]
