FROM envoyproxy/envoy:latest

RUN apt update && apt install -y curl tcpdump vim net-tools netcat 

RUN mkdir /code /etc/consul.d

COPY ./services/3rd/consul /usr/bin/
COPY ./services/envoy-xds/envoy-xds /usr/local/bin/envoy-xds
COPY ./services/envoy-xds/start_service.sh /usr/local/bin/start_service.sh

RUN chmod u+x /usr/local/bin/start_service.sh /usr/bin/consul

ENTRYPOINT ["sh", "/usr/local/bin/start_service.sh" ]
