FROM envoyproxy/envoy:latest

RUN apt update && apt install -y python3 python3-pip \
&& pip3 install --upgrade pip \
&& pip install grpcio googleapis-common-protos \
&& pip install consulate \
&& mkdir /code \
&& apt install -y netcat

RUN apt install -y curl tcpdump vim  net-tools

COPY ./services/proto/rpc/src/room_pb2* /code/
COPY ./services/roomsvr/service.py /code
COPY ./services/roomsvr/start_service.sh /usr/local/bin/start_service.sh
COPY ./services/3rd/consul /usr/bin/
COPY ./services/zonesvr/service-envoy.yaml /etc/service-envoy.yaml

RUN mkdir /etc/consul.d
RUN chmod u+x /usr/local/bin/start_service.sh /usr/bin/consul

ENTRYPOINT ["sh", "/usr/local/bin/start_service.sh" ]
