version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-http-gateway
    volumes:
      - ./services/front-gw/http-gateway.yaml:/etc/http-gateway.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
      - "5678"
    ports:
      - "8000:80"
      - "8001:8001"
      - "5678:5678"
  zonesvr:
    build:
      context: ./
      dockerfile: Dockerfile-zonesvr
    volumes:
      - ./services/zonesvr/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - zonesvr1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  roomsvr:
    build:
      context: ./
      dockerfile: Dockerfile-roomsvr
    volumes:
      - ./services/roomsvr/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - roomsvr1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  envoy-xds:
    build:
      context: ./
      dockerfile: Dockerfile-envoy-xds
    volumes:
      - ./services/envoy-xds/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - envoy-xds-1
    expose:
      - "18000"
    ports:
      - "18000:18000"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

  consul-server-1: &consul-server
    image: consul:latest
    networks:
      envoymesh:
        aliases:
          - consul-server-1
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    #command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    #  consul-server-2:
    #    <<: *consul-server
    #    networks:
    #      envoymesh:
    #        aliases:
    #          - consul-server-2
    #
    #  consul-server-3:
    #    <<: *consul-server
    #    networks:
    #      envoymesh:
    #        aliases:
    #          - consul-server-3
    #
    #  consul-server-4:
    #    <<: *consul-server
    #    networks:
    #      envoymesh:
    #        aliases:
    #          - consul-server-4

  consul-server-bootstrap:
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

networks:
  envoymesh: {}
