FROM envoyproxy/envoy:latest

RUN apt update && apt install -y curl tcpdump vim net-tools netcat 

CMD /usr/local/bin/envoy -c /etc/http-gateway.yaml --service-cluster front-proxy --service-node front-proxy --v2-config-only -l trace
