FROM envoyproxy/envoy:latest

RUN apt-get update && apt-get -q install -y curl
RUN apt install -y tcpdump net-tools

CMD /usr/local/bin/envoy -c /etc/http-gateway.yaml --service-cluster front-proxy --service-node front-proxy --v2-config-only -l debug
