FROM envoyproxy/envoy:latest

RUN apt update && apt install -y python3 python3-pip \
&& pip3 install --upgrade pip \
&& pip install -q Flask==0.11.1 requests==2.18.4 \
&& pip install grpcio googleapis-common-protos \
&& mkdir /code 

COPY ./service.py /code
COPY ./room_pb2* /code/
COPY ./start_service.sh /usr/local/bin/start_service.sh
COPY ./service-envoy.yaml /etc/service-envoy.yaml
COPY ./consul /usr/bin/

CMD chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
