FROM envoyproxy/envoy:latest

RUN apt update && apt install python3 python3-pip \
&& pip3 install --upgrade pip \
&& pip install grpcio googleapis-common-protos \
&& mkdir /code 

COPY ./service.py /code
COPY ./start_service.sh /usr/local/bin/start_service.sh
COPY ./room_pb2* /code

ENTRYPOINT /usr/local/bin/start_service.sh