# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import room_pb2 as room__pb2


class RoomServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRoom = channel.unary_unary(
        '/naruto.RoomService/GetRoom',
        request_serializer=room__pb2.RoomRequest.SerializeToString,
        response_deserializer=room__pb2.Room.FromString,
        )


class RoomServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRoom(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RoomServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRoom': grpc.unary_unary_rpc_method_handler(
          servicer.GetRoom,
          request_deserializer=room__pb2.RoomRequest.FromString,
          response_serializer=room__pb2.Room.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'naruto.RoomService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
